version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kinesis"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gdntn8kxr8xl"
s3_prefix = "kinesis"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FirehoseS3Prefix=\"firehose/\" FirehoseCompressionFormat=\"GZIP\" FirehoseBufferingInterval=\"60\" FirehoseBufferingSize=\"10\""
