AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test

  Sample SAM Template for sam-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Layers:
      - !Ref RuntimeDependenciesLayer
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-Pillow:13
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-pycryptodome:6
    Runtime: python3.8
    MemorySize: 128
    Timeout: 900

Parameters:
  FirehoseS3Prefix:
    Type: String
    Default: firehose/
    Description: "The S3 Key prefix for Kinesis Firehose."
  FirehoseS3PrefixTwitter:
    Type: String
    Default: twitter/
    Description: "The S3 Key prefix for Kinesis Firehose Twitter."
  FirehoseS3Prefix2:
    Type: String
    Default: firehose2/
    Description: "The S3 Key prefix for Kinesis Firehose specific"
  FirehoseCompressionFormat:
    Type: String
    Default: GZIP
    AllowedValues: [UNCOMPRESSED, GZIP, Snappy]
    Description: "Compression format used by Kinesis Firehose"
  FirehoseBufferingInterval:
    Type: Number
    Default: 60
    MinValue: 60
    MaxValue: 900
    Description: "How long Firehose will wait before writing a new batch into S3"
  FirehoseBufferingSize:
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 128
    Description: "Maximum batch size in MB"
  AthenaDatabaseName:
    Type: String
    Default: serverless_data_pipeline
    Description: "The Athena database name"
  AthenaTableName:
    Type: String
    Default: records
    Description: "The Athena table name"

Resources:

  IngestDataFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: ingest.lambda_handler
      Policies:
        - FirehoseCrudPolicy:
            DeliveryStreamName: !Ref DeliveryStream
      Events:
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
  
  IngestDataFunction2:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: ingest3.lambda_handler
      Policies:
        - FirehoseCrudPolicy:
            DeliveryStreamName: !Ref DeliveryStream2
      Events:
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
  
  GetPredictTextFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: predictText.lambda_handler
      Events:
        GetPredictTextAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /predictText
            Method: post
  
  GetPredictImageFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: predictImage.lambda_handler
      Events:
        GetPredictTextAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /predictImage
            Method: post


  IngestTwitterDataFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: ingestTwitter.lambda_handler
      Policies:
        - FirehoseCrudPolicy:
            DeliveryStreamName: !Ref DeliveryStreamTwitter
      Events:
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)

  DeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn:
      - DeliveryStreamPolicy
    Properties:
      DeliveryStreamName: "DeliveryStream"
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        Prefix: !Ref FirehoseS3Prefix
        BucketARN: !Join 
          - ''
          - - 'arn:aws:s3:::'
            - !Ref S3Records
        BufferingHints:
          IntervalInSeconds: !Ref FirehoseBufferingInterval
          SizeInMBs: !Ref FirehoseBufferingSize
        CompressionFormat: !Ref FirehoseCompressionFormat
        RoleARN: !GetAtt DeliveryStreamRole.Arn
  
  DeliveryStreamTwitter:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn:
      - DeliveryStreamPolicy
    Properties:
      DeliveryStreamName: "DeliveryStreamTwitter"
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        Prefix: !Ref FirehoseS3PrefixTwitter
        BucketARN: !Join 
          - ''
          - - 'arn:aws:s3:::'
            - !Ref S3Records
        BufferingHints:
          IntervalInSeconds: !Ref FirehoseBufferingInterval
          SizeInMBs: !Ref FirehoseBufferingSize
        CompressionFormat: !Ref FirehoseCompressionFormat
        RoleARN: !GetAtt DeliveryStreamRole.Arn
  
  DeliveryStream2:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn:
      - DeliveryStreamPolicy
    Properties:
      DeliveryStreamName: "DeliveryStream2"
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        Prefix: !Ref FirehoseS3Prefix2
        BucketARN: !Join 
          - ''
          - - 'arn:aws:s3:::'
            - !Ref S3Records
        BufferingHints:
          IntervalInSeconds: !Ref FirehoseBufferingInterval
          SizeInMBs: !Ref FirehoseBufferingSize
        CompressionFormat: !Ref FirehoseCompressionFormat
        RoleARN: !GetAtt DeliveryStreamRole.Arn

  DeliveryStreamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref 'AWS::AccountId'
  
  DeliveryStreamPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref DeliveryStreamRole
      PolicyName: firehose_delivery_policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:AbortMultipartUpload'
              - 's3:GetBucketLocation'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
              - 's3:PutObject'
            Resource:
              - !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3Records
              - !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3Records
                  - '*'
  
  CFNRoleFlights:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"

  MyCrawler2:
    Type: AWS::Glue::Crawler
    Properties:
      Name: "testcrawler1"
      Role: !GetAtt CFNRoleFlights.Arn
      DatabaseName: !Ref AthenaDatabaseName
      Targets:
        S3Targets:
          - Path: !Ref S3Records
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Schedule:
        ScheduleExpression: "cron(0/10 * ? * MON-FRI *)"
  
  AthenaCreateDatabaseQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Description: Run this query to initialize the Athena database
      QueryString: !Sub "CREATE DATABASE IF NOT EXISTS `${AthenaDatabaseName}`;"
      Database: !Ref AthenaDatabaseName

  AthenaCreateTableQuery:
    Type: AWS::Athena::NamedQuery
    DependsOn:
      - S3Records
    Properties:
      Description: Run this query to initialize the Athena table
      QueryString: !Sub >
        CREATE EXTERNAL TABLE IF NOT EXISTS `${AthenaDatabaseName}`.`${AthenaTableName}` (
          `url` string,
          `description` string,
          `location` string
        )
      Database: !Ref AthenaDatabaseName

  S3Records:
    Type: AWS::S3::Bucket
  
  # KinesisStream:
  #   Type: "AWS::Kinesis::Stream"
  #   Properties:
  #     ShardCount: 4

  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
        BuildMethod: makefile
    Properties:
      LayerName: "kenesis-dependencies"
      Description: Python Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - python3.8
      RetentionPolicy: Retain

  # # DynamoTable:
  # #   Type: AWS::DynamoDB::Table
  # #   Properties:
  # #     AttributeDefinitions:
  # #       -
  # #         AttributeName: "id"
  # #         AttributeType: "S"
  # #       -
  # #         AttributeName: "date"
  # #         AttributeType: "S"
  # #     KeySchema:
  # #       -
  # #         AttributeName: "id"
  # #         KeyType: "HASH"
  # #       -
  # #         AttributeName: "date"
  # #         KeyType: "RANGE"
  # #     ProvisionedThroughput:
  # #       ReadCapacityUnits: "1"
  # #       WriteCapacityUnits: "1"
  # #     TableName: "DynamoTable"
  
  # DDBFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: ddb/
  #     Policies:
  #       - DynamoDBCrudPolicy: {TableName: !Ref DDBRecords}
  #     Environment:
  #       Variables:
  #         TABLE: !Ref DDBRecords
  #     Events:
  #       Stream:
  #         Type: Kinesis
  #         Properties:
  #           Stream: !GetAtt DDBConsumer.ConsumerARN
  #           StartingPosition: LATEST
  #           BatchSize: 100
  
  # S3Function:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: s3/
  #     Policies:
  #       - S3CrudPolicy: {BucketName: !Ref S3Records}
  #     Environment:
  #       Variables:
  #         BUCKET: !Ref S3Records
  #     Events:
  #       Stream:
  #         Type: Kinesis
  #         Properties:
  #           Stream: !GetAtt S3Consumer.ConsumerARN
  #           StartingPosition: LATEST
  #           BatchSize: 100


  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  
  BucketName:
    Description: The bucket where data will be stored
    Value: !Ref S3Records
